LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := cryptodev-examples-aes
LOCAL_MODULE_TAGS := eng tests
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MULTILIB := 64
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../module
LOCAL_CFLAGS := -Wall
LOCAL_SRC_FILES := aes.c
LOCAL_SHARED_LIBRARIES :=
LOCAL_STATIC_LIBRARIES :=

include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)

LOCAL_MODULE := cryptodev-examples-fipsaes
LOCAL_MODULE_TAGS := eng tests
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MULTILIB := 64
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../module
LOCAL_CFLAGS := -Wall
LOCAL_SRC_FILES := fipsaes.c
LOCAL_SHARED_LIBRARIES :=
LOCAL_STATIC_LIBRARIES :=

include $(BUILD_EXECUTABLE)
